// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0PqzYqgL-erB59rOfUP6baEY4WOrNd64',
    appId: '1:36676552423:web:2968c958b6b6e36fea0442',
    messagingSenderId: '36676552423',
    projectId: 'firechatapp-10ff9',
    authDomain: 'firechatapp-10ff9.firebaseapp.com',
    storageBucket: 'firechatapp-10ff9.appspot.com',
    measurementId: 'G-ZJNWTWFFFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwst7BiDPtlI6o-XTdeQ1ba1IXgj3KFjk',
    appId: '1:36676552423:android:a921ed22d02e51aeea0442',
    messagingSenderId: '36676552423',
    projectId: 'firechatapp-10ff9',
    storageBucket: 'firechatapp-10ff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0n0npPN2kr-a4tg3ZCTVVgD1nuyaobVk',
    appId: '1:36676552423:ios:118cc0620b0457b9ea0442',
    messagingSenderId: '36676552423',
    projectId: 'firechatapp-10ff9',
    storageBucket: 'firechatapp-10ff9.appspot.com',
    iosBundleId: 'com.example.chatFirebaseMiner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0n0npPN2kr-a4tg3ZCTVVgD1nuyaobVk',
    appId: '1:36676552423:ios:4a4895fb1ae36a32ea0442',
    messagingSenderId: '36676552423',
    projectId: 'firechatapp-10ff9',
    storageBucket: 'firechatapp-10ff9.appspot.com',
    iosBundleId: 'com.example.chatFirebaseMiner.RunnerTests',
  );
}
